/*
    app.js
    code for our demo application
 */

"use strict";


angular.module('ToDoApp', [])
    .config(function($httpProvider) {
        //Parse required two extra headers sent with every HTTP request: X-Parse-Application-Id, X-Parse-REST-API-Key
        //the first needs to be set to your application's ID value
        //the second needs to be set to your application's REST API key
        //both of these are generated by Parse when you create your application via their web site
        //the following lines will add these as default headers so that they are sent with every
        //HTTP request we make in this application
        $httpProvider.defaults.headers.common['X-Parse-Application-Id'] = 'g2c4vTb64Mx9vZ0ov9foep288oHlvi6uBN0TtTQb';
        $httpProvider.defaults.headers.common['X-Parse-REST-API-Key'] = 'ygvDT8uIurcj0NyqM6jR6ndx2lY8tsBi60LgVDLs';
    })
    .controller('TasksController', function($scope, $http) {
        //when people click Refresh button in index page AND automatically when this script loads for the first time
        $scope.refreshTasks = function() {
            //sets the loading icon to spin 
            $scope.loading = true; 
            //get the task that have been saved to parse 
            $http.get('https://api.parse.com/1/classes/tasks' + '?where={"done": false}') //send other piece of info where I only want to see task that are done 
                    .success(function(responseData){
                    //when return a list of data
                     $scope.tasks = responseData.results; //always get response data 
                })
                    .error(function(err) {
                        console.log(err); 
                        //notify the user in some way
                    })
                    .finally(function() {
                        $scope.loading = false; 
                }); 

        }; //scope.refreshTasks

        $scope.refreshTasks(); 

        //set newTask.done = false
        $scope.newTask = {  done: false };

        //rating system set to 0 every new time
        $scope.newTask = {vote: 0}; 



        //function to add a new task to the list
        $scope.addTask = function(task) {
            $scope.inserting = true;
            //POST will add (insert) a new item to the class
            $http.post('https://api.parse.com/1/classes/tasks', task)
                .success(function(responseData) {
                    console.log("success!!!");
                    //Parse.com will return then new objectID in the response data 
                    //copt that to the task we just inserted
                    task.objectID = responseData.objectId; 

                    $scope.tasks.push(task); //add task to local list 
                    $scope.newTask = {done: false}; 
                })
                .error(function(err) {
                    console.log(err);
                    //report to user in some way
                })
                .finally(function() {
                    $scope.inserting = false;
                });
        } 
        //function to update an existing task
        $scope.updateTask = function(task) {
            $scope.updating = true; 
            //location to update and pass information that is change task is updating task.ObjectID
            $http.put('https://api.parse.com/1/classes/tasks' + task.objectId, task)
            .success(function(task) {
                //put command automatically updates the correct task (task.objectId) with the
                //correct updates (task)
                //nothing we really need to do since local object is already up-to-date
            })

            .error(function(err) {
                console.log(err); 
                //notify the user in some way
            })
            .finally(function() {
                $scope.updating = false;
            });
        } 
        $scope.upVote = function(task) {

            var upVoteYay = { 
                vote: {__op: 'Increment', amount: 1}
            };

            //wrap everything into a function 
            $http.put('https://api.parse.com/1/classes/tasks/' + task.objectId, upVoteYay)
                .success(function(responseData){
                    $scope.refreshTasks();

                })
                .error(function(err) {
                    console.log(err); 
                })
        }
    });

